services:
  db:
    image: postgres:17
    container_name: postgres_db
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"
    volumes:
      - db-data:/var/lib/postgresql/data
      - ./sql:/docker-entrypoint-initdb.d
    restart: always
    networks:
      - backend

volumes:
  db-data:
    driver: local
    driver_opts:
        type: none
        device: ./data/pgdata
        o: bind 
    labels:
      com.example.description: "database"  
      com.example.department: "Laboratorio Bioinformática"  
      com.example.label-with-empty-value: "" 

networks:
  backend:
    driver: bridge