"""fix users

Revision ID: 70214c367626
Revises: 3d46dd1b3f53
Create Date: 2024-10-07 09:44:14.638108

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '70214c367626'
down_revision = '3d46dd1b3f53'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('usuarios', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'tipos_usuario', ['tipo_usuario'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('usuarios', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')

    # ### end Alembic commands ###
